org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897
org.gradle.java.installations.paths=C:\\Users\\Administrator\\.gradle\\jdks\\jdk-17.0.2
systemProp.net.minecraftforge.gradle.check.certs=false